[package]
name = "ecostats"
version = "0.1.0"
authors = ["André Arko <andre@arko.net>"]

[dependencies]
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
time = "0.1"
nom = "4.0"
regex = "1"